name: DDC
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50406
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1a1a1a'
    - '#323232'
    - '#3f3f3f'
    - '#626262'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
